name: Core Contracts Slither Analysis
on:
  push:
    branches:
      - main
      - release-v*
  pull_request: {}
  workflow_dispatch: {}

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - run: npm install --global yarn
      - run: yarn install
      - name: Prepare project
        run: yarn buildPrepare
      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        id: slither
        continue-on-error: true
        with:
          node-version: 16
          ignore-compile: true
          sarif: results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
